### ISSUE TITLE
Define datadisk size under host definitions

### ISSUE THREAD

**Issue by tahonen** [ivanthelad/ansible-azure#31]
Now disk sizes are defined in *-avail.json files. It would be nice to externalize those to all file.

Something like this

```
jumphost:
  jumphost1:
    name: jumphost1
    datadisksize: 128
    tags:
      region: northeurope
      zone: jumphost
      stage: jumphost

masters:
  master1:
    name: master1
    datadisksize: 40
    tags:
      region: northeurope
      zone: infra
      stage: none

infranodes:
  infranode1:
    name: infranode1
    datadisksize: 20
    tags:
      region: northeurope
      zone: infra
      stage: dev
```

and then in *-avail.json files

```
...
"vmDatadiskSize": {
      "type": "string",
      "defaultValue": "40"
 },
...
"dataDisks": [
            {
              "caching": "None",
              "createOption": "Empty",
              "diskSizeGB": "[parameters('vmDatadiskSize')]",
              "lun": 0,
              "name": "[parameters('vmName')]",
              "vhd": {
                "uri": "[concat('http://', variables('sa'), '.blob.core.cloudapi.de/openshiftvmachines/', parameters('vmName'), '_datadisk1.vhd')]"
              }
            }
          ]
...
```
